name: Test wf
on:
  push:
    branches: ['main']
jobs:
  call_workflow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ['main', 'develop']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: 'smaeyamada/github_wf'
          ref: ${{ matrix.branch }}

      - name: check2
        run: |
          cat README.md
          cd ./.github/
          ls -a
          cd ./workflows/ && pwd
          ls -a

      - name: get wf
        run: |
          cd
          cd cd ./.github/
          mkdir actions
          cd actions
          curl https://raw.githubusercontent.com/smaeyamada/github_wf/develop/.github/workflows/wf.yml > action.yml
          cat action.yml
