name: Test wf
on:
  push:
    branches: ['main']
jobs:
  call_workflow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ['main', 'develop']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: 'smaeyamada/github_wf'
          ref: ${{ matrix.branch }}

      - name: check
        run: |
          ls -al

      - name: Checkout path
        uses: actions/checkout@v3
        with:
          repository: 'smaeyamada/github_wf'
          path: '.github/workflows'

      - name: check2
        run: |
          ls -al
          cat README.md
          ls -al .github/workflows
          cat .github/workflows/wf.yml
