name: Test wf
on:
  push:
    branches: ['main']
jobs:
  call_workflow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ['main', 'develop']
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: 'smaeyamada/github_wf'
          ref: ${{ matrix.branch }}

      - name: check2
        run: |
          cat README.md
          cd ./.github/
          ls -a
          cd ./workflows/ && pwd
          ls -a
          cat wf.yml

      # - name: get wf
      #   run: |
      #     cd
      #     cd ./.github/
      #     mkdir actions
      #     cd actions
      #     curl https://raw.githubusercontent.com/smaeyamada/github_wf/${{ matrix.branch }}/.github/workflows/wf.yml > action.yml
      #     cat action.yml

      - name: call wf
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/smaeyamada/github_wf/actions/workflows/wf.yml/dispatches" \
            -d '{"ref":"${{ matrix.branch }}","inputs":{"cache_flg":"false"}}'
          echo "status: $?"
